/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobType = IDL.Variant({
  'remote' : IDL.Null,
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const Time = IDL.Int;
export const JobListing = IDL.Record({
  'title' : IDL.Text,
  'salaryCurrency' : IDL.Text,
  'jobType' : JobType,
  'jobId' : IDL.Text,
  'description' : IDL.Text,
  'district' : IDL.Text,
  'company' : IDL.Text,
  'state' : IDL.Text,
  'datePosted' : Time,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
});
export const JobApplication = IDL.Record({
  'applicantName' : IDL.Text,
  'applicationId' : IDL.Text,
  'jobId' : IDL.Text,
  'submittedAt' : Time,
  'coverLetter' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ApplicationResult = IDL.Variant({
  'ok' : IDL.Text,
  'error' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobById' : IDL.Func([IDL.Text], [JobListing], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ApplicationResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobType = IDL.Variant({
    'remote' : IDL.Null,
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const Time = IDL.Int;
  const JobListing = IDL.Record({
    'title' : IDL.Text,
    'salaryCurrency' : IDL.Text,
    'jobType' : JobType,
    'jobId' : IDL.Text,
    'description' : IDL.Text,
    'district' : IDL.Text,
    'company' : IDL.Text,
    'state' : IDL.Text,
    'datePosted' : Time,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
  });
  const JobApplication = IDL.Record({
    'applicantName' : IDL.Text,
    'applicationId' : IDL.Text,
    'jobId' : IDL.Text,
    'submittedAt' : Time,
    'coverLetter' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ApplicationResult = IDL.Variant({
    'ok' : IDL.Text,
    'error' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobById' : IDL.Func([IDL.Text], [JobListing], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ApplicationResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };