/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationResult = { 'ok' : string } |
  { 'error' : string };
export interface JobApplication {
  'applicantName' : string,
  'applicationId' : string,
  'jobId' : string,
  'submittedAt' : Time,
  'coverLetter' : string,
  'email' : string,
  'phone' : string,
}
export interface JobListing {
  'title' : string,
  'salaryCurrency' : string,
  'jobType' : JobType,
  'jobId' : string,
  'description' : string,
  'district' : string,
  'company' : string,
  'state' : string,
  'datePosted' : Time,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
}
export type JobType = { 'remote' : null } |
  { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllJobs' : ActorMethod<[], Array<JobListing>>,
  'getApplicationsForJob' : ActorMethod<[string], Array<JobApplication>>,
  'getJobById' : ActorMethod<[string], JobListing>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string],
    ApplicationResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];