/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VacancyStatus = IDL.Variant({
  'new' : IDL.Null,
  'old' : IDL.Null,
  'draft' : IDL.Null,
});
export const JobType = IDL.Variant({
  'remote' : IDL.Null,
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const Time = IDL.Int;
export const JobListing = IDL.Record({
  'status' : VacancyStatus,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'salaryCurrency' : IDL.Text,
  'jobType' : JobType,
  'city' : IDL.Text,
  'jobId' : IDL.Text,
  'description' : IDL.Text,
  'district' : IDL.Text,
  'company' : IDL.Text,
  'state' : IDL.Text,
  'datePosted' : Time,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
});
export const JobApplication = IDL.Record({
  'applicantName' : IDL.Text,
  'applicationId' : IDL.Text,
  'jobId' : IDL.Text,
  'submittedAt' : Time,
  'coverLetter' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ApplicationResult = IDL.Variant({
  'ok' : IDL.Text,
  'error' : IDL.Text,
});

export const idlService = IDL.Service({
  'countJobTypes' : IDL.Func(
      [],
      [
        IDL.Record({
          'remote' : IDL.Nat,
          'contract' : IDL.Nat,
          'partTime' : IDL.Nat,
          'fullTime' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getApplicationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobById' : IDL.Func([IDL.Text], [IDL.Opt(JobListing)], ['query']),
  'getJobCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getVacanciesByStatus' : IDL.Func(
      [VacancyStatus],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'postVacancy' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        VacancyStatus,
      ],
      [IDL.Text],
      [],
    ),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ApplicationResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VacancyStatus = IDL.Variant({
    'new' : IDL.Null,
    'old' : IDL.Null,
    'draft' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'remote' : IDL.Null,
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const Time = IDL.Int;
  const JobListing = IDL.Record({
    'status' : VacancyStatus,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'salaryCurrency' : IDL.Text,
    'jobType' : JobType,
    'city' : IDL.Text,
    'jobId' : IDL.Text,
    'description' : IDL.Text,
    'district' : IDL.Text,
    'company' : IDL.Text,
    'state' : IDL.Text,
    'datePosted' : Time,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
  });
  const JobApplication = IDL.Record({
    'applicantName' : IDL.Text,
    'applicationId' : IDL.Text,
    'jobId' : IDL.Text,
    'submittedAt' : Time,
    'coverLetter' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ApplicationResult = IDL.Variant({
    'ok' : IDL.Text,
    'error' : IDL.Text,
  });
  
  return IDL.Service({
    'countJobTypes' : IDL.Func(
        [],
        [
          IDL.Record({
            'remote' : IDL.Nat,
            'contract' : IDL.Nat,
            'partTime' : IDL.Nat,
            'fullTime' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getApplicationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobById' : IDL.Func([IDL.Text], [IDL.Opt(JobListing)], ['query']),
    'getJobCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getVacanciesByStatus' : IDL.Func(
        [VacancyStatus],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'postVacancy' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          VacancyStatus,
        ],
        [IDL.Text],
        [],
      ),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ApplicationResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };